khanMap = {
	'derivative':['visualizing_derivatives',
					'antiderivatives',
					'applications-of-derivatives--motion-along-a-line',
					'applications-of-derivatives--tangent-and-normal-lines',
					'derivative_intuition',
					'derivatives-of-inverse-functions',
					'graphs-of-functions-and-their-derivatives',
					'second-derivative-test',
					'special_derivatives',
					'the-formal-and-alternate-form-of-the-derivative'
					],
	'z score':['z_scores_1',
				'z_scores_2',
				'z_scores_3'],
	'riemann sum':['the-definite-integral-as-the-limit-of-a-riemann-sum',
					'riemann-sums-and-sigma-notation',
					'using-rectangles-to-approximate-area-under-a-curve'],
	'fundamental theorem of calculus':['the-fundamental-theorem-of-calculus'],
	'power rule':['power_rule'],
	'power series':['creating-power-series-from-geometric-series-using-algebra',
						'creating-power-series-from-geometric-series-using-differentiation-and-integration'],
	'taylor series':['finding-taylor-series'],
	'integration':['integration',
					'integration-and-differentiation-of-power-series',
					'integration-by-parts',
					'integration-by-the-reverse-chain-rule',
					'integration-by-u-substitution',
					'integration-of-rational-functions-by-division-and-partial-fractions',
					'integration-using-trigonometric-identities',
					'integration-using-trigonometric-substitution'
					],
	'limits':['limits-at-infinity-where-f-x--is-unbounded',
				'limits-at-infinity-where-x-is-unbounded',
				'limits_2',
				'one-sided-limits-from-graphs',
				'two-sided-limits-from-graphs',
				'two-sided-limits-using-algebra'],
	'parametric curves':['parametric-equations-and-their-graphs',
							'slope-and-arc-length-of-parametric-curves'
							],
	'mean value theorem':['mean-value-theorem'],
	'product rule':['product_rule'],
	'l hopitals rule':['lhopitals_rule'],
	'quotient rule':['quotient_rule'],
	'implicit differentiation':['implicit-differentiation'],
	'optimization problem':['optimization'],
	'integration by substitution':['integration-by-u-substitution',
									'integration-using-trigonometric-substitution'],
	'improper integrals':['improper-integrals']
}