khanMap = {
	'derivative':['visualizing_derivatives',
					'antiderivatives',
					'applications-of-derivatives--motion-along-a-line',
					'applications-of-derivatives--tangent-and-normal-lines',
					'derivative_intuition',
					'derivatives-of-inverse-functions',
					'graphs-of-functions-and-their-derivatives',
					'second-derivative-test',
					'special_derivatives',
					'the-formal-and-alternate-form-of-the-derivative'
					],
	'z score':['z_scores_1',
				'z_scores_2',
				'z_scores_3'],
	'riemann sum':['the-definite-integral-as-the-limit-of-a-riemann-sum',
					'riemann-sums-and-sigma-notation',
					'using-rectangles-to-approximate-area-under-a-curve'],
	'fundamental theorem of calculus':['the-fundamental-theorem-of-calculus'],
	'power rule':['power_rule'],
	'power series':['creating-power-series-from-geometric-series-using-algebra',
						'creating-power-series-from-geometric-series-using-differentiation-and-integration'],
	'taylor series':['finding-taylor-series'],
	'integration':['integration',
					'integration-and-differentiation-of-power-series',
					'integration-by-parts',
					'integration-by-the-reverse-chain-rule',
					'integration-by-u-substitution',
					'integration-of-rational-functions-by-division-and-partial-fractions',
					'integration-using-trigonometric-identities',
					'integration-using-trigonometric-substitution'
					],
	'limits':['limits-at-infinity-where-f-x--is-unbounded',
				'limits-at-infinity-where-x-is-unbounded',
				'limits_2',
				'one-sided-limits-from-graphs',
				'two-sided-limits-from-graphs',
				'two-sided-limits-using-algebra'],
	'parametric curves':['parametric-equations-and-their-graphs',
							'slope-and-arc-length-of-parametric-curves'
							],
	'mean value theorem':['mean-value-theorem'],
	'product rule':['product_rule'],
	'l hopitals rule':['lhopitals_rule'],
	'quotient rule':['quotient_rule'],
	'implicit differentiation':['implicit-differentiation'],
	'optimization problem':['optimization'],
	'integration by substitution':['integration-by-u-substitution',
									'integration-using-trigonometric-substitution'],
	'improper integrals':['improper-integrals'],
	'expected value':['expected-value-with-empirical-probabilities',
						'expected-value-with-calculated-probabilities',
						'making-decisions-with-expected-values',
						'expected_value'],
	'standard deviation':['standard_deviation_of_a_population',
							'standard_deviation'],
	'empirical':['empirical_rule'],
	'set notation':['basic_set_notation'],
	'probability':['probability_with_perm_comb','multiplying-dependent-probabilities','expected-value-with-calculated-probabilities','expected-value-with-empirical-probabilities','using-probability-to-make-fair-decisions','probability_1','finding-probability','understanding-probability','using-probability-to-make-predictions','probability-models','independent_probability','adding-probability','constructing-probability-distributions','dependent_probability','multiplying-dependent-probabilities'],
	'hypothesis testing':['hypothesis-testing-in-experiments','hypothesis-testing-with-simulations'],
	'scatter plots':['fitting-functions-to-scatter-plots','constructing-scatter-plots','making-good-scatter-plots','positive-and-negative-linear-correlations-from-scatter-plots','interpreting-scatter-plots'],
	'linear regression':['linear-models-of-bivariate-data','interpreting-slope-and-y-intercept-of-lines-of-best-fit','plotting_the_line_of_best_fit','correlation-coefficient-intuition'],
	'variance':['variance'],
	'permutations':['permutations_and_combinations_2','permutations_1','probability_with_perm_comb'],
	'combinations':['permutations_and_combinations_2','combinations_1','probability_with_perm_comb']
}

codecademyMap = {}