courseConcepts = {
	'statistics' : [
		'z score',
		'central limit theorem',
		'expected value',
		'mean',
		'median',
		'mode',
		'empirical rule',
		'scatter plot',
		'set notation',
		'hypothesis testing',
		'linear regression',
		'variance'
	],

	"calculus" : [
	    "derivative",
	    "remann sum",
	    "fundamental theorem of calculus",
	    "taylor series",
	    "integration",
	    "limits",
	    "parametric curves",
	    "mean value theorem",
	    "product rule",
	    "l hopitals rule",
	    "quotient rule",
	    "implicit differentiation",
	    "optimization problem",
	    "integration by substitution",
	    "improper integrals",
	    "eulers method",
	    "seperable differential equations",
	    "slope fields",
	    "integration by parts",
	    "integration by u substitution",
	    "the fundamental theorem of calculus",
	    "ratio test",
	    "alternating series",
	    "convergence",
	    "divergence",
	    "power rule",
	    "squeeze theorem"
	],

	'probability' : [
		'expected value',
		'markov chains',
		'probability',
		'permutations',
		'combinations',
		'sample space',
		'conditional probability',
		'random variables',
		'bayes rule',
		'continuous variables',
		'discrete variables',
		'weak law of large numbers',
		'law of large numbers',
		'bernoulli process',
		'poisson process',
		'central limit theorem'
	],

	"algorithms" : [
	    "insertion sort",
	    "mergesort",
	    "horners rule",
	    "divide and conquer",
	    "quick sort",
	    "heap sort",
	    "bucket sort",
	    "asymptotic notation",
	    "radix sort",
	    "hashing",
	    "hash functions",
	    "binary search trees",
	    "black red trees",
	    "2-3 trees",
	    "b trees",
	    "range trees",
	    "interval trees",
	    "dijkstras algorithm",
	    "o notation",
	    "selection sort",
	    "recursion",
	    "towers of hanoi",
	    "breadth first",
	    "depth first"
	    "avl trees",
	    "avl sort",
	    "computational complexity"
	],

	"data structures" : [
		"linked list",
		"stack",
		"queue",
		"binary tree",
		"binary search tree",
		"heap",
		"hashing",
		"graph",
		"array",
		"matrix"
	],
	"discrete mathematics" : [
		"truth table",
		"de morgans law"
	],
	"programming languages" : [
		"python",
		"ruby",
		"javascript",
		"c#",
		".net",
		"rails",
		"nodejs",
		"c++",
		"c",
		"java",
		"haskell",
		"go",
		"php",
		"rust"
	],
	"object oriented programming" : [
		"inheritance"
	],
	"web development" : [
		"api",
		"oauth",
		"http",
		"cookies"
	]
}